[package]
name = "inline-rt-hlsl"
version.workspace = true
edition.workspace = true

[dependencies]
metal.workspace = true
winit.workspace = true
objc.workspace = true
cocoa.workspace = true
libloading.workspace = true
saxaboom.workspace = true